# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: music.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='music.proto',
  package='lark',
  syntax='proto3',
  serialized_pb=_b('\n\x0bmusic.proto\x12\x04lark\"\xa3\x02\n\tPianoRoll\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0f\x63ollection_name\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x12\n\nresolution\x18\x04 \x01(\x05\x12\x12\n\ntotal_tick\x18\x05 \x01(\x03\x12%\n\x06tracks\x18\x06 \x03(\x0b\x32\x15.lark.PianoRoll.Track\x1a\x8f\x01\n\x05Track\x12\x0c\n\x04name\x18\x01 \x01(\t\x12)\n\x05notes\x18\x02 \x03(\x0b\x32\x1a.lark.PianoRoll.Track.Note\x1aM\n\x04Note\x12\x10\n\x08velocity\x18\x01 \x01(\x05\x12\r\n\x05pitch\x18\x02 \x01(\x05\x12\x12\n\nstart_tick\x18\x03 \x01(\x03\x12\x10\n\x08\x65nd_tick\x18\x04 \x01(\x03\x62\x06proto3')
)




_PIANOROLL_TRACK_NOTE = _descriptor.Descriptor(
  name='Note',
  full_name='lark.PianoRoll.Track.Note',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='velocity', full_name='lark.PianoRoll.Track.Note.velocity', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='lark.PianoRoll.Track.Note.pitch', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_tick', full_name='lark.PianoRoll.Track.Note.start_tick', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_tick', full_name='lark.PianoRoll.Track.Note.end_tick', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=313,
)

_PIANOROLL_TRACK = _descriptor.Descriptor(
  name='Track',
  full_name='lark.PianoRoll.Track',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='lark.PianoRoll.Track.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notes', full_name='lark.PianoRoll.Track.notes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PIANOROLL_TRACK_NOTE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=313,
)

_PIANOROLL = _descriptor.Descriptor(
  name='PianoRoll',
  full_name='lark.PianoRoll',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='lark.PianoRoll.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collection_name', full_name='lark.PianoRoll.collection_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='lark.PianoRoll.filename', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='lark.PianoRoll.resolution', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_tick', full_name='lark.PianoRoll.total_tick', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracks', full_name='lark.PianoRoll.tracks', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PIANOROLL_TRACK, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=313,
)

_PIANOROLL_TRACK_NOTE.containing_type = _PIANOROLL_TRACK
_PIANOROLL_TRACK.fields_by_name['notes'].message_type = _PIANOROLL_TRACK_NOTE
_PIANOROLL_TRACK.containing_type = _PIANOROLL
_PIANOROLL.fields_by_name['tracks'].message_type = _PIANOROLL_TRACK
DESCRIPTOR.message_types_by_name['PianoRoll'] = _PIANOROLL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PianoRoll = _reflection.GeneratedProtocolMessageType('PianoRoll', (_message.Message,), dict(

  Track = _reflection.GeneratedProtocolMessageType('Track', (_message.Message,), dict(

    Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), dict(
      DESCRIPTOR = _PIANOROLL_TRACK_NOTE,
      __module__ = 'music_pb2'
      # @@protoc_insertion_point(class_scope:lark.PianoRoll.Track.Note)
      ))
    ,
    DESCRIPTOR = _PIANOROLL_TRACK,
    __module__ = 'music_pb2'
    # @@protoc_insertion_point(class_scope:lark.PianoRoll.Track)
    ))
  ,
  DESCRIPTOR = _PIANOROLL,
  __module__ = 'music_pb2'
  # @@protoc_insertion_point(class_scope:lark.PianoRoll)
  ))
_sym_db.RegisterMessage(PianoRoll)
_sym_db.RegisterMessage(PianoRoll.Track)
_sym_db.RegisterMessage(PianoRoll.Track.Note)


# @@protoc_insertion_point(module_scope)
